// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEFlPmb4aEKPUCWw7DzHRQqKvM1rvfgXw',
    appId: '1:242774020378:web:2a14dc6dd3e78ff6099ca3',
    messagingSenderId: '242774020378',
    projectId: 'beeware-beaef',
    authDomain: 'beeware-beaef.firebaseapp.com',
    storageBucket: 'beeware-beaef.firebasestorage.app',
    measurementId: 'G-W1HFTD0L49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaBsw-AfLOBBQgXhJkE0L_bDehow6TyFg',
    appId: '1:242774020378:android:376c3ceea19b1279099ca3',
    messagingSenderId: '242774020378',
    projectId: 'beeware-beaef',
    storageBucket: 'beeware-beaef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArzeU5QMtiFbnsYdkZOkoYmEiS0XK-Ge8',
    appId: '1:242774020378:ios:025803eeae02d30a099ca3',
    messagingSenderId: '242774020378',
    projectId: 'beeware-beaef',
    storageBucket: 'beeware-beaef.firebasestorage.app',
    iosBundleId: 'com.example.beewareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArzeU5QMtiFbnsYdkZOkoYmEiS0XK-Ge8',
    appId: '1:242774020378:ios:025803eeae02d30a099ca3',
    messagingSenderId: '242774020378',
    projectId: 'beeware-beaef',
    storageBucket: 'beeware-beaef.firebasestorage.app',
    iosBundleId: 'com.example.beewareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEFlPmb4aEKPUCWw7DzHRQqKvM1rvfgXw',
    appId: '1:242774020378:web:24bff9d6b4bdf71d099ca3',
    messagingSenderId: '242774020378',
    projectId: 'beeware-beaef',
    authDomain: 'beeware-beaef.firebaseapp.com',
    storageBucket: 'beeware-beaef.firebasestorage.app',
    measurementId: 'G-MZLGH1LEQM',
  );
}
